site_name: Bia Language
use_directory_urls: false
theme:
  name: material
  font: false
  palette:
    scheme: preference
    primary: blue grey
    accent: blue grey
  language: en
markdown_extensions:
  - admonition
  - pymdownx.tasklist:
      custom_checkbox: true
  - pymdownx.tilde
  - pymdownx.caret
  - pymdownx.tabbed
  - pymdownx.inlinehilite
  - pymdownx.superfences
  - pymdownx.highlight:
      linenums: true
  - footnotes
nav:
  - Home: index.md
  - Introduction:
      - Getting Started: Introduction/Getting Started.md
      - Embedding: Introduction/Embedding.md
      - Cheatsheet: Introduction/Cheatsheet.md
  - Types:
    - Numbers: Types/Numbers.md
    - Strings: Types/Strings.md
    - Regex: Types/Regex.md
    - List: Types/List.md
  - Examples:
    - Hello World: Examples/Hello World.md
  - Syntax:
    - Comments: Syntax/Comments.md
    - Operators: Syntax/Operators.md
  - Engine:
    - Engine: Engine/Engine.md
    - Memory: Engine/Memory.md
    - Stack: Engine/Stack.md
    - Op Codes: Engine/Op Codes.md
  - Specification:
    - Variables: Specification/Variables.md
    - Flow Control: Specification/Flow Control.md
    - Scopes: Specification/Scopes.md
    - Keywords: Specification/Keywords.md
repo_name: bialang/bia
repo_url: https://github.com/bialang/bia
