site_name: Bia Language
use_directory_urls: false
theme:
  name: material
  font: false
markdown_extensions:
  - admonition
  - pymdownx.tasklist:
      custom_checkbox: true
  - pymdownx.tilde
  - pymdownx.caret
  - codehilite
  - footnotes
nav:
  - Home: index.md
  - Introduction:
      - Getting Started: Introduction/Getting Started.md
      - Embedding: Introduction/Embedding.md
      - Cheatsheet: Introduction/Cheatsheet.md
  - Types:
    - Numbers: Types/Numbers.md
    - Strings: Types/Strings.md
    - Regex: Types/Regex.md
  - Examples:
    - Hello World: Examples/Hello World.md
  - Syntax:
    - Comments: Syntax/Comments.md
    - Operators: Syntax/Operators.md
  - Engine:
    - Engine: Engine/Engine.md
    - Memory: Engine/Memory.md
    - Op Codes: Engine/Op Codes.md
  - Specification:
    - Variables: Specification/Variables.md
    - Flow Control: Specification/Flow Control.md
    - Scopes: Specification/Scopes.md
repo_name: bialang/bia
repo_url: https://github.com/bialang/bia
